# Generated by Django 5.2.7 on 2025-10-31 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursLangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=100, verbose_name='Nom du Cours')),
                ('langue_enseignee', models.CharField(max_length=50, verbose_name='Langue Enseignée')),
                ('description_programme', models.TextField()),
            ],
            options={
                'verbose_name': 'Cours de Langue',
                'verbose_name_plural': 'Cours de Langue',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=150, verbose_name="Nom de l'Établissement")),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(max_length=100, unique=True, verbose_name='Nom du Pays')),
                ('continent', models.CharField(max_length=50)),
                ('description_generale', models.TextField(verbose_name='Description Générale du Pays')),
            ],
            options={
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='TypeVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_visa', models.CharField(max_length=50, unique=True, verbose_name='Nom du Visa')),
                ('description_courte', models.TextField()),
            ],
            options={
                'verbose_name': 'Type de Visa',
            },
        ),
        migrations.CreateModel(
            name='FiliereEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=150, verbose_name='Nom de la Filière')),
                ('domaine_etude', models.CharField(max_length=100)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.etablissement')),
            ],
            options={
                'verbose_name': "Filière d'Étude",
                'verbose_name_plural': "Filières d'Étude",
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.pays'),
        ),
        migrations.CreateModel(
            name='Scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_etude', models.CharField(max_length=50, verbose_name="Niveau d'Étude (ex: Master 1)")),
                ('duree_annee', models.IntegerField(default=1, verbose_name='Durée (années)')),
                ('frais_scolarite', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Frais de Scolarité')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.filiereetude')),
            ],
        ),
        migrations.CreateModel(
            name='SectionHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(max_length=50, verbose_name='Nom de la Section (ex: Soir, Intensif)')),
                ('jours_semaine', models.CharField(max_length=100, verbose_name='Jours (ex: Lun-Mer-Ven)')),
                ('heure_debut', models.TimeField(verbose_name='Heure de Début')),
                ('duree_heures', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Durée (heures)')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de Début (optionnel)')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.courslangue')),
            ],
            options={
                'verbose_name': 'Section et Horaire',
                'verbose_name_plural': 'Sections et Horaires',
            },
        ),
        migrations.CreateModel(
            name='VisaParPays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation', models.TextField(verbose_name='documentation')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.pays')),
                ('type_visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.typevisa')),
            ],
            options={
                'verbose_name': 'Visa par Pays',
                'verbose_name_plural': 'Visas par Pays',
                'unique_together': {('pays', 'type_visa')},
            },
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_disponible', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('ville_emploi', models.CharField(max_length=100)),
                ('salaire_annuel_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salaire_annuel_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exigences_specifiques', models.TextField(verbose_name='Exigences du Poste')),
                ('visa_pays', models.ForeignKey(limit_choices_to={'type_visa__nom_visa': 'Travail'}, on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.visaparpays', verbose_name='Lien Visa Travail')),
            ],
            options={
                'verbose_name': "Offre d'Emploi",
                'verbose_name_plural': "Offres d'Emploi",
            },
        ),
    ]
