# Generated by Django 5.2.7 on 2025-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='drapeau',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image du Drapeau'),
        ),
    ]
