# Generated by Django 5.2.7 on 2025-11-03 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0002_pays_drapeau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.TextField(verbose_name='reduction')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.pays')),
                ('type_visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.typevisa')),
            ],
            options={
                'verbose_name': 'Visa par Pays',
                'verbose_name_plural': 'Visas par Pays',
                'unique_together': {('pays', 'type_visa')},
            },
        ),
    ]
