# Generated by Django 5.2.7 on 2025-11-06 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0003_promotions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotions',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='visa_pays',
            field=models.ForeignKey(limit_choices_to={'type_visa__nom_visa': 'Visa travail'}, on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.visaparpays', verbose_name='Lien Visa Travail'),
        ),
    ]
