# Generated by Django 5.2.7 on 2025-11-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0004_alter_promotions_options_alter_offreemploi_visa_pays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='pays',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='visa_pays',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_visa__nom_visa': 'Visa etudiant'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bright_consulting.visaparpays', verbose_name='Lien Visa Etudiant'),
        ),
    ]
