# Generated by Django 5.2.7 on 2025-11-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0005_remove_etablissement_pays_etablissement_visa_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='VictoireVoyageur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_voyageur', models.CharField(max_length=100, verbose_name='Nom complet du Voyageur')),
                ('metier', models.CharField(max_length=100, verbose_name='Métier ou Profession')),
                ('pays_destination', models.CharField(max_length=100, verbose_name="Pays d'Arrivée (Destination)")),
                ('photo', models.ImageField(upload_to='victoires_photos/', verbose_name='Photo du Voyageur')),
                ('type_visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bright_consulting.typevisa', verbose_name='Type de Visa Obtenu')),
            ],
            options={
                'verbose_name': 'Victoire de Voyageur',
                'verbose_name_plural': 'Victoires des Voyageurs',
            },
        ),
    ]
