# Generated by Django 5.2.7 on 2025-11-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0006_victoirevoyageur'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisVoyageur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_auteur', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Non Public)')),
                ('contenu_avis', models.TextField(verbose_name='Votre Avis/Témoignage')),
                ('note', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Note (sur 5)')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé pour publication')),
            ],
            options={
                'verbose_name': 'Avis Voyageur',
                'verbose_name_plural': 'Avis des Voyageurs',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
