# Generated by Django 5.2.7 on 2025-11-08 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0007_avisvoyageur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courslangue',
            name='langue_enseignee',
        ),
    ]
