# Generated by Django 5.2.7 on 2025-11-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0008_remove_courslangue_langue_enseignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image du Drapeau')),
                ('titre', models.CharField(max_length=100, verbose_name="Titre de l'article")),
                ('description', models.TextField()),
                ('avis_entreprise', models.TextField()),
            ],
            options={
                'verbose_name': "Titre de L'article",
                'verbose_name_plural': 'Titres des articles',
            },
        ),
    ]
