# Generated by Django 5.2.7 on 2025-11-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0009_articledeblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledeblog',
            options={'verbose_name': 'Articles de blog', 'verbose_name_plural': 'Articles de blog'},
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='nom_entreprise',
        ),
        migrations.RemoveField(
            model_name='offreemploi',
            name='ville_emploi',
        ),
        migrations.RemoveField(
            model_name='pays',
            name='description_generale',
        ),
        migrations.RemoveField(
            model_name='visaparpays',
            name='documentation',
        ),
    ]
