# Generated by Django 5.2.7 on 2025-11-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0010_alter_articledeblog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiereetude',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='scolarite',
            name='filiere',
        ),
        migrations.DeleteModel(
            name='Etablissement',
        ),
        migrations.DeleteModel(
            name='Scolarite',
        ),
    ]
