# Generated by Django 5.2.7 on 2025-11-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bright_consulting', '0011_remove_filiereetude_etablissement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offreemploi',
            old_name='salaire_annuel_max',
            new_name='salaire_mensuel_max',
        ),
        migrations.RenameField(
            model_name='offreemploi',
            old_name='salaire_annuel_min',
            new_name='salaire_mensuel_min',
        ),
    ]
